# Generated by Django 2.2 on 2020-12-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201214_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
